export const DailyGoals = {
  WATER_ML: 2700,
  WATER_BOTTLES: 3,
  WATER_BOTTLE_DEFAULT_ML: 900,
  FOOD_MEALS: 3,
  BATHROOM_NORMAL_MIN: 4,
  BATHROOM_NORMAL_MAX: 10,
  HEALTH_ENERGY_CHECKINS: 2,
  HEALTH_TARGET_ENERGY: 6,
  SLEEP_MIN_HOURS: 7,
  SLEEP_MAX_HOURS: 9,
  SLEEP_IDEAL_HOURS: 8,
  EMOTIONS_CHECKINS: 2,
  INTERACTIONS_MIN: 1,
  CHORES_TASKS_MIN: 3,
  CHORES_COMPLETION_TARGET: 0.65,
  HOBBIES_DAILY_MIN: 20,
  HOBBIES_WEEKLY_MIN: 120
} as const
